# Generated by Django 5.1.2 on 2025-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
