# Generated by Django 5.1.2 on 2025-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_tasks_lat_tasks_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='lon',
            field=models.FloatField(blank=True),
        ),
    ]
