# Generated by Django 5.1.2 on 2025-05-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_tasks_lat_alter_tasks_lon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='Task',
        ),
    ]
