# Generated by Django 5.2.1 on 2025-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_task_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
