# Generated by Django 6.0.4 on 2026-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_alter_pushsubscription_user_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='location_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='time_notified',
            field=models.BooleanField(default=False),
        ),
    ]
